### ISSUE TITLE
部署 TTRSS 时提示 Please set SELF_URL_PATH to the correct value for your server

### ISSUE THREAD

**Issue by FledgeXu** [HenryQW/docker-ttrss-plugins#19]
docker-compose 摘录如下

```
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
            - 181:80
    environment:
      - SELF_URL_PATH=http://feed.mydomin.com/
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=*********
    stdin_open: true
    tty: true
    restart: always
```
我把SELF_URL_PATH改成 `http://ip/`也无法启动。

这是为什么？

**Comment by HenryQW** [comment]
所以你是需要 ip 直接访问？ 地址 http://ip:181/

**Comment by FledgeXu** [comment]
我刚刚试了一下还是不行。依旧提示我要输入地址。

**Comment by HenryQW** [comment]
麻烦贴配置，部署环境。

这就是为什么开 issue 要遵循模板

![image](https://user-images.githubusercontent.com/5896343/54615096-67766a00-4a55-11e9-8b8f-35a59e5ceecc.png)

**Comment by FledgeXu** [comment]
对不起，issue 开的太匆忙，没有注意到。

OS 信息:
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
安装方式：
```
docker-compose 
```
Postgres 版本：
```
psql (PostgreSQL) 9.6.11
```

错误提示：
```
ttrss              | You might want to check tt-rss wiki or the forums for more information.
ttrss              | Please search the forums before creating new topic for your question.
ttrss              | Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade.
ttrss              | Please fix errors indicated by the following messages:
ttrss              |
ttrss              |  * Please set SELF_URL_PATH to the correct value for your server (possible value: <b>http://</b>)
```

配置文件
```
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
            - 181:80
    environment:
      - SELF_URL_PATH=http://139.162.42.137:181/
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=7y8rWf5wrFM2Vj
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    expose:
      - 3000
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      NODE_ENV: production
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
            - 181:80
    environment:
      - SELF_URL_PATH=http://139.162.42.137:181/
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=7y8rWf5wrFM2Vj
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    expose:
      - 3000
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      NODE_ENV: production
version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
            - 181:80
    environment:
      - SELF_URL_PATH=http://139.162.42.137:181/
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=*************
    stdin_open: true
    tty: true
    restart: always

  service.mercury: # set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    expose:
      - 3000
    restart: always

  service.opencc: # set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      NODE_ENV: production
    expose:
      - 3000
    restart: always

**Comment by FledgeXu** [comment]
我试了一下直接用 docker run 运行，结果也是一样。

**Comment by HenryQW** [comment]
刚跑的，没有任何问题：

```yml
version: "3"
services:
  database.postgres:
    image: sameersbn/postgresql:latest
    container_name: postgres
    environment:
      - PG_PASSWORD=ttrss # please change the password
      - DB_EXTENSION=pg_trgm
    restart: always

  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 181:80
    environment:
      - SELF_URL_PATH=http://localhost:181/ # please change to your own domain
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=ttrss # please change the password
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for database.postgres:5432 -- php /configure-db.php && exec s6-svscan /etc/s6/'
```

![image](https://user-images.githubusercontent.com/5896343/54679657-bd075100-4aff-11e9-98d7-ca99418eb45a.png)
